#!/bin/bash

# NOTE: ONLY RUN THIS AFTER FIRST GENERATING THE ASSETS IN VISUAL STUDIO
# DO NOT RE-RUN
exit

#
# Some of the images generated by the Visual Studio manifest/asset
# generator come out too large. They need to be under 204800 bytes.
# This script converts all images from RGB to indexed palette while maintaining the alpha channels.
# The largest of the images (LargeTile.scale-400.png) comes out around 177 kB.

cd Images

set -x

for i in *; do
    pngquant --ordered 20 --force --ext .png "$i"
done
