#!/bin/bash

# Once the Visual Assets have been autogenerated in Visual Studio from the
# large box cover image, we find the box cover image is too detailed to
# scale below about 100x100.
#
# This script goes through all of the autogenerated images in the Images/
# directory. Any image that is less than 100x100 is replaced with a scaled
# version of the plain ship icon (from 128x128.png). Any image larger than
# that is replaced by a scaled version of the box cover image. Wide images
# are regenerated by scaling the box cover image and adding black
# letterboxing to left/right.

cover=../../icons/cover-image2Gc.png
ship=../../icons/128x128.png

for i in Images/*; do
    echo "===== Processing: $i ====="
    w=$(file "$i"  | awk '{ if (match($0, /([0-9]*) x /, m)) { print m[1]; }}')
    h=$(file "$i"  | awk '{ if (match($0, /x ([0-9]*)/, m)) { print m[1]; }}')
    echo "  Existing size: ${w}x${h}"
    # Replace images that are too small
    if (( w == h && w < 100 )); then
	echo "  Replacing small icon with ship icon at ${w}x${h}"
	convert -resize "${w}x${h}" "$ship" "PNG32:$i"
    elif (( w == h )); then
	echo "  Regenerating from cover image at ${w}x${h}"
	convert -resize "${w}x${h}" "$cover" tmp.png
	# Keep images under 204 kB
	pngquant --ordered 20 --force --ext .png tmp.png
	mv tmp.png "$i"
    elif (( w > h )); then
	echo "  Changing letterboxing to black"
	m=$(((w - h) / 2))
	convert -resize ${w}x${h} -gravity Center -extent ${h}x${h} -border ${m}x0 -bordercolor black "$cover" tmp.png
	# Keep images under 204 kB
	pngquant --ordered 20 --force --ext .png tmp.png
	mv tmp.png "$i"
    fi
done
